config/routes.rb
SilentAuction::Application.routes.draw do

  root 'application#index'

  # Auction screen
  get 'auction', to: 'auction#index', as: 'auction'
  get 'results/:page', to: 'auction#results', as: 'results'
  get 'amount_raised', to: 'auction#amount_raised'
  get 'time_left', to: 'auction#time_left'

  # Administration
  get 'admin', to: 'admin#index'
  get 'import_items', to: 'admin#import_items'
  get 'import_users', to: 'admin#import_users'
  get 'user_cards', to: 'admin#user_cards'
  get 'highest_bids', to: 'admin#highest_bids'
  get 'all_receipts', to: 'admin#all_receipts'
  post 'import_items_google_drive', to: 'admin#import_items_google_drive'
  post 'import_tables_google_drive', to: 'admin#import_tables_google_drive'

  resources :preferences
  resources :user_groups
  resources :users
  resources :items
  resources :bids

  # Authentication
  get 'authenticate', to: 'authentication#tables', as: 'authenticate_select_table'
  get 'authenticate/:id', to: 'authentication#users', as: 'authenticate_select_user'
  get 'authenticate/:id/pin', to: 'authentication#user_pin', as: 'user_pin'
  post 'authenticate/:id/pin', to: 'authentication#user_pin'

  # iPad bidding
  get 'select_table', to: 'host_bid#select_table', as: 'select_table'
  get 'select_user/:table_id', to: 'host_bid#select_user', as: 'select_user'
  get 'select_item/:user_id', to: 'host_bid#select_item', as: 'select_item'
  get 'select_amount/:user_id/:item_id', to: 'host_bid#select_amount', as: 'select_amount'
  post 'place_bid/:user_id/:item_id', to: 'host_bid#place_bid', as: 'place_host_bid'

  # Users interface
  get 'all_items', to: 'user_bid#all_items', as: 'all_items'
  get 'current_bids', to: 'user_bid#current_bids', as: 'current_bids'
  post 'place_bid', to: 'user_bid#place_bid', as: 'place_user_bid'
  get 'legend', to: 'user_bid#legend', as: 'legend'

  devise_for :user, :path => '', :path_names => { :sign_in => "authenticate" }

end

app/views/admin/index.html.erb
<h1>Administration</h1>

<%= link_to user_groups_path, html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-user">Manage Tables</i>
<% end %>

<br/>

<%= link_to users_path, html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-user">Manage Users</i>
<% end %>

<br/>

<%= link_to items_path, html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-list-alt">Manage Items</i>
<% end %>

<br/>

<%= link_to bids_path, html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-usd">Manage Bids</i>
<% end %>

<br/>

<%= link_to preferences_path, html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-list-alt">Manage Preferences</i>
<% end %>

<br/>
<hr/>

<%= link_to user_cards_path, html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-user">Export user cards (HTML)</i>
<% end %>
<br/>
<%= link_to "#{user_cards_path}.pdf", html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-user">Export user cards (PDF)</i>
<% end %>
<br/>
<%= link_to "#{highest_bids_path}.csv", html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-usd">Export highest bids (CSV)</i>
<% end %>
<br/>
<%= link_to "#{all_receipts_path}.pdf", html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-usd">Generate receipts (PDF)</i>
<% end %>

<br/>
<hr/>
<br/>

<%= form_tag(import_items_google_drive_path) do -%>
  <%= text_field_tag 'username', nil, placeholder: 'Google username' %>
  <%= password_field_tag 'password', nil, placeholder: 'Google password' %>
  <%= submit_tag 'Import Items from Google Drive', class: "btn btn-primary" %>
<% end -%>

<br/>

<%= form_tag(import_tables_google_drive_path) do -%>
  <%= text_field_tag 'username', nil, placeholder: 'Google username' %>
  <%= password_field_tag 'password', nil, placeholder: 'Google password' %>
  <%= submit_tag 'Import Tables from Google Drive', class: "btn btn-primary" %>
<% end -%>

<br/>

<%= link_to import_items_path, html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-share">Import Items (Local copy)</i>
<% end %>

<br/>

<%= link_to import_users_path, html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-share">Import Tables (Local copy)</i>
<% end %>

app/views/admin/user_cards.erb
<div class="container">
	<% @users.each do |user| %>
    <div class="col-md-4 user-card">
      <div class="card-top">
        <div class="ufe-logo">
          <%= image_tag("ufe_logo.png") %>
        </div>
        <div class="card-detail">
          <div class="card-header">
            Silent Auction
          </div>
          <div class="username">
            <%= user.title %> <%= user.first_name %> <%= user.last_name %>
          </div>
          <div class="user-pin">
            PIN: <%= user.pin %>
          </div>
        </div>
      </div>
      <div class="card-footer">
        Charity Gala UFE 2013
      </div>
      </div>
  <% end %>
</div>

app/views/admin/user_cards.html.erb
<div class="container">
	<% @users.each do |user| %>
    <div class="col-md-4 user-card">
      <div class="card-top">
        <div class="ufe-logo">
          <%= image_tag("ufe_logo.png") %>
        </div>
        <div class="card-detail">
          <div class="card-header">
            Silent Auction
          </div>
          <div class="username">
            <%= user.title %> <%= user.first_name %> <%= user.last_name %>
          </div>
          <div class="user-pin">
            PIN: <%= user.pin %>
          </div>
        </div>
      </div>
      <div class="card-footer">
        Charity Gala UFE 2013
      </div>
      </div>
  <% end %>
</div>