config/routes.rb
SilentAuction::Application.routes.draw do

  root 'application#index'

  # Auction screen
  get 'auction', to: 'auction#index', as: 'auction'
  get 'results/:page', to: 'auction#results', as: 'results'
  get 'amount_raised', to: 'auction#amount_raised'
  get 'time_left', to: 'auction#time_left'

  # Administration
  get 'admin', to: 'admin#index'
  get 'import_items', to: 'admin#import_items'
  get 'import_users', to: 'admin#import_users'
  get 'user_cards', to: 'admin#user_cards'
  get 'highest_bids', to: 'admin#highest_bids'
  get 'all_receipts', to: 'admin#all_receipts'
  post 'import_items_google_drive', to: 'admin#import_items_google_drive'
  post 'import_tables_google_drive', to: 'admin#import_tables_google_drive'

  resources :preferences
  resources :user_groups
  resources :users
  resources :items
  resources :bids

  # Authentication
  get 'authenticate', to: 'authentication#tables', as: 'authenticate_select_table'
  get 'authenticate/:id', to: 'authentication#users', as: 'authenticate_select_user'
  get 'authenticate/:id/pin', to: 'authentication#user_pin', as: 'user_pin'
  post 'authenticate/:id/pin', to: 'authentication#user_pin'

  # iPad bidding
  get 'select_table', to: 'host_bid#select_table', as: 'select_table'
  get 'select_user/:table_id', to: 'host_bid#select_user', as: 'select_user'
  get 'select_item/:user_id', to: 'host_bid#select_item', as: 'select_item'
  get 'select_amount/:user_id/:item_id', to: 'host_bid#select_amount', as: 'select_amount'
  post 'place_bid/:user_id/:item_id', to: 'host_bid#place_bid', as: 'place_host_bid'

  # Users interface
  get 'all_items', to: 'user_bid#all_items', as: 'all_items'
  get 'current_bids', to: 'user_bid#current_bids', as: 'current_bids'
  post 'place_bid', to: 'user_bid#place_bid', as: 'place_user_bid'
  get 'legend', to: 'user_bid#legend', as: 'legend'

  devise_for :user, :path => '', :path_names => { :sign_in => "authenticate" }

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  has_many :users
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_filter :authenticate_admin!
  
  before_action :set_user_group, only: [:show, :edit, :update, :destroy]

  # GET /user_groups
  # GET /user_groups.json
  def index
    @user_groups = UserGroup.all.order(:sort_order)
  end

  # GET /user_groups/1
  # GET /user_groups/1.json
  def show
  end

  # GET /user_groups/new
  def new
    @user_group = UserGroup.new
  end

  # GET /user_groups/1/edit
  def edit
  end

  # POST /user_groups
  # POST /user_groups.json
  def create
    @user_group = UserGroup.new(user_group_params)

    respond_to do |format|
      if @user_group.save
        flash[:message] = "Table has been created"
        format.html { redirect_to edit_user_group_path(@user_group) }
        format.json { render action: 'show', status: :created, location: @user_group }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_groups/1
  # PATCH/PUT /user_groups/1.json
  def update
    respond_to do |format|
      if @user_group.update(user_group_params)
        flash[:message] = "Table has been updated"
        format.html { redirect_to edit_user_group_path(@user_group) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.json
  def destroy
    @user_group.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_group
      @user_group = UserGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_group_params
      params.require(:user_group).permit(:name, :sort_order)
    end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<%= form_for(@user_group, html: {role: "form", class: "form-inline"}) do |f| %>
  <% if @user_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

      <ul>
      <% @user_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-xs-2">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group col-xs-1">
    <%= f.label :sort_order %>
    <%= f.text_field :sort_order %>
  </div>

  <div class="actions form-group col-xs-2">
    <%= f.label :update %>
    <%= f.submit :id => 'user_group_update', :class => 'form-control btn btn-primary' %>
  </div>
<% end %>

app/views/user_groups/edit.html.erb
<h1>Editing user_group</h1>

<%= link_to admin_path, html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-home">Administration</i>
<% end %>
<br/>
<%= link_to user_groups_path, html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-user">Manage Tables</i>
<% end %>

<%= render 'form' %>

app/views/user_groups/index.html.erb
<h1>Listing user_groups</h1>

<%= link_to admin_path, html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-home">Administration</i>
<% end %>

<br/>

<%= link_to new_user_group_path, html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-plus">New Table</i>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Sort order</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_groups.each do |user_group| %>
      <tr>
        <td><%= user_group.name %></td>
        <td><%= user_group.sort_order %></td>
        <td><%= button_to 'Edit', edit_user_group_path(user_group), method: :get, :class => 'btn btn-primary' %></td>
        <td><%= button_to 'Delete', user_group, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/user_groups/new.html.erb
<h1>New user_group</h1>

<%= render 'form' %>

<%= link_to 'Back', user_groups_path %>