config/routes.rb
SilentAuction::Application.routes.draw do

  root 'application#index'

  # Auction screen
  get 'auction', to: 'auction#index', as: 'auction'
  get 'results/:page', to: 'auction#results', as: 'results'
  get 'amount_raised', to: 'auction#amount_raised'
  get 'time_left', to: 'auction#time_left'

  # Administration
  get 'admin', to: 'admin#index'
  get 'import_items', to: 'admin#import_items'
  get 'import_users', to: 'admin#import_users'
  get 'user_cards', to: 'admin#user_cards'
  get 'highest_bids', to: 'admin#highest_bids'
  get 'all_receipts', to: 'admin#all_receipts'
  post 'import_items_google_drive', to: 'admin#import_items_google_drive'
  post 'import_tables_google_drive', to: 'admin#import_tables_google_drive'

  resources :preferences
  resources :user_groups
  resources :users
  resources :items
  resources :bids

  # Authentication
  get 'authenticate', to: 'authentication#tables', as: 'authenticate_select_table'
  get 'authenticate/:id', to: 'authentication#users', as: 'authenticate_select_user'
  get 'authenticate/:id/pin', to: 'authentication#user_pin', as: 'user_pin'
  post 'authenticate/:id/pin', to: 'authentication#user_pin'

  # iPad bidding
  get 'select_table', to: 'host_bid#select_table', as: 'select_table'
  get 'select_user/:table_id', to: 'host_bid#select_user', as: 'select_user'
  get 'select_item/:user_id', to: 'host_bid#select_item', as: 'select_item'
  get 'select_amount/:user_id/:item_id', to: 'host_bid#select_amount', as: 'select_amount'
  post 'place_bid/:user_id/:item_id', to: 'host_bid#place_bid', as: 'place_host_bid'

  # Users interface
  get 'all_items', to: 'user_bid#all_items', as: 'all_items'
  get 'current_bids', to: 'user_bid#current_bids', as: 'current_bids'
  post 'place_bid', to: 'user_bid#place_bid', as: 'place_user_bid'
  get 'legend', to: 'user_bid#legend', as: 'legend'

  devise_for :user, :path => '', :path_names => { :sign_in => "authenticate" }

end

app/models/preference.rb
class Preference < ActiveRecord::Base
	def self.end_time
    end_time_preference = Preference.where(name: 'END_TIME').first
    DateTime.strptime(end_time_preference.value, '%Y-%m-%d %H:%M:%S%z')
  end

  def as_json(options={})
    {
      name: name,
      value: value
    }
  end
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_action :set_preference, only: [:show, :edit, :update, :destroy]

  # GET /preferences
  # GET /preferences.json
  def index
    @preferences = Preference.all
  end

  # GET /preferences/1
  # GET /preferences/1.json
  def show
  end

  # GET /preferences/new
  def new
    @preference = Preference.new
  end

  # GET /preferences/1/edit
  def edit
  end

  # POST /preferences
  # POST /preferences.json
  def create
    @preference = Preference.new(preference_params)

    respond_to do |format|
      if @preference.save
        flash[:message] = "Preference has been created"
        format.html { redirect_to edit_preference_path(@preference) }
        format.json { render action: 'show', status: :created, location: @preference }
      else
        format.html { render action: 'new' }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preferences/1
  # PATCH/PUT /preferences/1.json
  def update
    respond_to do |format|
      if @preference.update(preference_params)
        flash[:message] = "Preference has been updated"
        format.html { redirect_to edit_preference_path(@preference) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preferences/1
  # DELETE /preferences/1.json
  def destroy
    @preference.destroy
    respond_to do |format|
      format.html { redirect_to preferences_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preference
      @preference = Preference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preference_params
      params.require(:preference).permit(:name, :value)
    end
end

app/views/preferences/_form.html.erb
<%= form_for(@preference, html: {role: "form", class: "form-inline"}) do |f| %>
  <% if @preference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@preference.errors.count, "error") %> prohibited this preference from being saved:</h2>

      <ul>
      <% @preference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-xs-2">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group col-xs-3">
    <%= f.label :value %><br>
    <%= f.text_field :value, :class => 'form-control' %>
  </div>
  <div class="form-group actions col-xs-2">
    <%= f.label :update %>
    <%= f.submit :id => 'preference_update', :class => 'form-control btn btn-primary' %>
  </div>
<% end %>

app/views/preferences/edit.html.erb
<h1>Editing preference</h1>

<%= link_to admin_path, html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-home">Administration</i>
<% end %>
<br/>
<%= link_to preferences_path, html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-list-alt">Manage Preferences</i>
<% end %>

<%= render 'form' %>

app/views/preferences/index.html.erb
<h1>Listing preferences</h1>

<%= link_to admin_path, html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-home">Administration</i>
<% end %>

<br/>

<%= link_to new_preference_path, html_options = {class: "btn"} do %>
  <i class="glyphicon glyphicon-plus">New Preference</i>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @preferences.each do |preference| %>
      <tr>
        <td><%= preference.name %></td>
        <td><%= preference.value %></td>
        <td><%= button_to 'Edit', edit_preference_path(preference), method: :get, :class => 'btn btn-primary' %></td>
        <td><%= button_to 'Delete', preference, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Preference', new_preference_path %>

app/views/preferences/new.html.erb
<h1>New preference</h1>

<%= render 'form' %>

<%= link_to 'Back', preferences_path %>