config/routes.rb
SilentAuction::Application.routes.draw do

  root 'application#index'

  # Auction screen
  get 'auction', to: 'auction#index', as: 'auction'
  get 'results/:page', to: 'auction#results', as: 'results'
  get 'amount_raised', to: 'auction#amount_raised'
  get 'time_left', to: 'auction#time_left'

  # Administration
  get 'admin', to: 'admin#index'
  get 'import_items', to: 'admin#import_items'
  get 'import_users', to: 'admin#import_users'
  get 'user_cards', to: 'admin#user_cards'
  get 'highest_bids', to: 'admin#highest_bids'
  get 'all_receipts', to: 'admin#all_receipts'
  post 'import_items_google_drive', to: 'admin#import_items_google_drive'
  post 'import_tables_google_drive', to: 'admin#import_tables_google_drive'

  resources :preferences
  resources :user_groups
  resources :users
  resources :items
  resources :bids

  # Authentication
  get 'authenticate', to: 'authentication#tables', as: 'authenticate_select_table'
  get 'authenticate/:id', to: 'authentication#users', as: 'authenticate_select_user'
  get 'authenticate/:id/pin', to: 'authentication#user_pin', as: 'user_pin'
  post 'authenticate/:id/pin', to: 'authentication#user_pin'

  # iPad bidding
  get 'select_table', to: 'host_bid#select_table', as: 'select_table'
  get 'select_user/:table_id', to: 'host_bid#select_user', as: 'select_user'
  get 'select_item/:user_id', to: 'host_bid#select_item', as: 'select_item'
  get 'select_amount/:user_id/:item_id', to: 'host_bid#select_amount', as: 'select_amount'
  post 'place_bid/:user_id/:item_id', to: 'host_bid#place_bid', as: 'place_host_bid'

  # Users interface
  get 'all_items', to: 'user_bid#all_items', as: 'all_items'
  get 'current_bids', to: 'user_bid#current_bids', as: 'current_bids'
  post 'place_bid', to: 'user_bid#place_bid', as: 'place_user_bid'
  get 'legend', to: 'user_bid#legend', as: 'legend'

  devise_for :user, :path => '', :path_names => { :sign_in => "authenticate" }

end

app/controllers/host_bid_controller.rb
class HostBidController < MobileApplicationController
  before_filter :authenticate_user!, :authenticate_admin!

  def select_table
    @user_groups = UserGroup.all.order(:sort_order).to_a
  end

  def select_user
    @users = User.where('user_group_id = ?', params['table_id']).order('last_name, first_name')
  end

  def select_item
    @items = Item.all.order(:code).to_a
    @user = User.find(params[:user_id])
  end

  def select_amount
    @item = Item.find(params[:item_id])
    @user = User.find(params[:user_id])
  end

  def place_bid
    begin
      item = Item.find(params[:item_id])
      user = User.find(params[:user_id])
      bid = Bid.place(item, user, params[:price].to_d, current_user)
      flash[:message] = "Bid has been placed at $#{params[:price]}"
      render json: {success: true, item: item, user: current_user, bid: bid}
    rescue Exception => e
      render json: {success: false, message: e.message, minimum_price: item.minimum_price, current_price: item.current_price}
    end
  end

end

app/views/host_bid/select_amount.html.erb
<%= render partial: 'common/host_header' %>

<div id="bid" class="container" ng-controller="HostBidsCtrl" ng-init="init(<%= @user.id =%>, <%= @item.id =%>, <%= @item.current_price =%>, <%= @item.minimum_price =%>)">

  <div class="row">
    <div class="col-md-12 bid-title">
      <h1>
        <%= link_to select_item_path(user_id: @user.id), html_options = {class: "btn btn-primary btn-lg"} do %>
          <i class="glyphicon glyphicon-chevron-left">Back</i>
        <% end %>
        Place Bid
      </h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 bid-user">
      <span class="name">Guest: </span>
      <span class="value"><%= @user.title %> <%= @user.first_name %> <%= @user.last_name %></span>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 bid-item">
      <span class="name">Package: </span>
      <span class="value"><%= @item.code %> - <%= @item.name %></span>
    </div>
  </div>

  <div class="bid-amount">
    <div class="row">
      <div class="col-md-12">
        <div class="bid-price">
          <span class="name">Bid price: </span>
          <span class="current-price">{{biddingPrice | roundedCurrency}}</span>
        </div>
      </div>
      <div ng-show="currentPrice == defaultPrice" class="col-md-12 sub-price">
        <div class="bid-current-price">Start price: {{currentPrice | roundedCurrency}}</div>
      </div>
      <div ng-hide="currentPrice == defaultPrice" class="col-md-12 sub-price">
        <div class="bid-current-price">Current price: {{currentPrice | roundedCurrency}}</div>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-md-12 bid-actions">
      <button class="btn btn-default btn-lg" type="submit" ng-click="refresh()">
        <span class="glyphicon glyphicon-refresh"></span><span class="btn-bid">Reset</span>
      </button>
      <button class="btn btn-default btn-lg" type="submit" ng-click="add(<%= @item.bid_increment %>)">
        <span class="glyphicon glyphicon-plus"></span><span class="btn-bid">$<%= @item.bid_increment %></span>
      </button>
    </div>
  </div>

  <div class="row" ng-show="error != ''">
    <div class="col-md-12">&nbsp;</div>
    <div class="bid-message alert alert-danger">{{error}}</div>
  </div>

  <div class="row"><div class="col-md-12">&nbsp;</div></div>

  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-5"></div>
        <div class="col-md-2">
          <button id="submit-bid" type="submit" class="btn btn-primary btn-lg btn-success" ng-click="placeBid()">
            <span class="glyphicon glyphicon-usd"></span> Place Bid
          </button>
        </div>
        <div class="col-md-5"></div>
      </div>
    </div>
  </div>

</div>

app/views/host_bid/select_item.html.erb
<%= render partial: 'common/host_header' %>

<div id="items" class="container list">
  <div class="row header-row">
    <div class="col-md-12">
      <h3>
        <%= link_to select_user_path(table_id: @user.user_group.id), html_options = {class: "btn btn-primary btn-lg"} do %>
          <i class="glyphicon glyphicon-chevron-left">Back</i>
        <% end %>
        Place a bid - Select prize
      </h3>
    </div>
  </div>

  <% @items.each_with_index do |item, index| %>
    <div class="col-md-12 list-item mask<%= index%8 + 1 %>">
      <%= link_to select_amount_path(user_id: params[:user_id], item_id: item.id) do %>
        <span class="glyphicon glyphicon-chevron-right pull-right"></span>
        <%= "#{item.code} - #{item.name}" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/host_bid/select_table.html.erb
<%= render partial: 'common/host_header' %>

<% if flash[:message] %>
  <div id="success" class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= flash[:message] %>
  </div>
<% end %>

<div id="tables" class="container list">
  <div class="row header-row">
    <div class="col-md-12">
      <h3>
        <%= link_to select_table_path, html_options = {class: "btn btn-primary btn-lg"} do %>
          <i class="glyphicon glyphicon-chevron-left">Back</i>
        <% end %>
        Place a bid - Select table
      </h3>
    </div>
  </div>

  <% @user_groups.each_with_index do |user_group, index| %>
  <div class="col-md-12 list-item mask<%= index%8 + 1 %>">
    <%= link_to select_user_path(table_id: user_group.id) do %>
    	<span class="glyphicon glyphicon-chevron-right pull-right"></span>
      <%= user_group.name %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/host_bid/select_user.html.erb
<%= render partial: 'common/host_header' %>

<div id="users" class="container list">
  <div class="row header-row">
    <div class="col-md-12">
      <h3>
        <%= link_to select_table_path, html_options = {class: "btn btn-primary btn-lg"} do %>
          <i class="glyphicon glyphicon-chevron-left">Back</i>
        <% end %>
        Place a bid - Select guest
      </h3>
    </div>
  </div>

  <% @users.each_with_index do |user, index| %>
    <div class="col-md-12 list-item mask<%= index%8 + 1 %>">
      <%= link_to select_item_path(user_id: user.id) do %>
        <span class="glyphicon glyphicon-chevron-right pull-right"></span>
        <%= "#{user.title} #{user.first_name} #{user.last_name}" %>
      <% end %>
    </div>
  <% end %>
</div>